version: '3'

networks: 
  appnet:
    ipam:
      config:
        - subnet: 172.24.0.0/16

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - appnet
    depends_on:
      - api
    volumes: 
      - ./static:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  api:
    restart: always  
    build:
      dockerfile: Dockerfile
      context: ./api
    networks:
      - appnet
    ports:
      - '8080'
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://172.17.0.1:5432/trails